Adapt httpboot plugin to respond with client specific UKIs
ironcore-dev/FeDHCP pull request #155
Opened 2024-06-06 09:41 UTC by hardikdr

# Proposed Changes

Fixes #

2024-06-06 09:46 UTC, hardikdr commented
cc @damyan @5kt

2024-06-17 10:11 UTC, damyan requested changes

2024-06-17 10:11 UTC, damyan commented on plugins/httpboot/plugin.go
> +			return resp, true
Same

2024-06-17 10:11 UTC, damyan commented on plugins/httpboot/plugin.go
> +			return resp, true
Change to false, so if your plugin fails for whatever reason, the plugin chain will not break (meaning: the next plugin in the configuration will get executed)

2024-06-17 10:11 UTC, damyan commented on plugins/httpboot/plugin.go
> +		return resp, true
Same

2024-06-17 10:43 UTC, hardikdr commented on plugins/httpboot/plugin.go
> +			return resp, true
Done

2024-06-17 10:43 UTC, hardikdr commented on plugins/httpboot/plugin.go
> +		return resp, true
Done

2024-06-17 10:44 UTC, 5kt approved these changes

2024-06-17 10:45 UTC, damyan approved these changes

2024-06-17 10:45 UTC, merged